/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"

	"bitbucket.org/free5gc-team/smf/logger"
	"bitbucket.org/free5gc-team/smf/service"
	"bitbucket.org/free5gc-team/version"
)

var SMF = &service.SMF{}

var appLog *logrus.Entry

func main() {
	app := cli.NewApp()
	app.Name = "smf"
	app.Usage = "-free5gccfg common configuration file -smfcfg smf configuration file -logpath log path -logname merged log file name"
	app.Action = action
	app.Flags = SMF.GetCliCmd()
	if err := app.Run(os.Args); err != nil {
		fmt.Printf("SMF Run error: %v\n", err)
	}
}

func action(c *cli.Context) error {
	if err := SMF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("Failed to initialize !!")
	}

	appLog = logger.AppLog
	appLog.Infoln(c.App.Name)
	appLog.Infoln("SMF version: ", version.GetVersion())

	SMF.Start()

	return nil
}
