/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pdusession

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi"
	"free5gc/lib/openapi/models"
	"free5gc/src/smf/handler/message"
	"free5gc/src/smf/logger"
	"free5gc/src/smf/producer"
	"github.com/gin-gonic/gin"
	"log"
	"net/http"
	"strconv"
	"strings"
)

// ReleaseSmContext - Release SM Context
func ReleaseSmContext(c *gin.Context) {
	logger.PduSessLog.Info("Recieve Release SM Context Request")
	var request models.ReleaseSmContextRequest
	request.JsonData = new(models.SmContextReleaseData)

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}
	if err != nil {
		log.Print(err)
		return
	}

	req := http_wrapper.NewRequest(c.Request, request)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	msg := message.NewHandlerMessage(message.PDUSessionSMContextRelease, req)
	message.SendMessage(msg)

	_ = <-msg.ResponseChan

	c.Status(http.StatusNoContent)

}

// RetrieveSmContext - Retrieve SM Context
func RetrieveSmContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateSmContext - Update SM Context
func UpdateSmContext(c *gin.Context) {
	logger.PduSessLog.Info("Recieve Update SM Context Request")
	var request models.UpdateSmContextRequest
	request.JsonData = new(models.SmContextUpdateData)

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}
	if err != nil {
		log.Print(err)
		return
	}

	req := http_wrapper.NewRequest(c.Request, request)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	msg := message.NewHandlerMessage(message.PDUSessionSMContextUpdate, req)
	smContextRef := msg.HTTPRequest.Params["smContextRef"]
	seqNum, ResBody := producer.HandlePDUSessionSMContextUpdate(
		msg.ResponseChan, smContextRef, msg.HTTPRequest.Body.(models.UpdateSmContextRequest))
	response := http_wrapper.Response{
		Status: http.StatusOK,
		Body:   ResBody,
	}
	logger.PduSessLog.Infoln("In UpdateSmContext")
	logger.PduSessLog.Infoln("Seq num: ", strconv.Itoa(int(seqNum)))
	message.RspQueue.PutItem(seqNum, msg.ResponseChan, response)

	rsp := <-msg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	if HTTPResponse.Status < 300 {
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	} else {
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}
}
